Repository iotaledger/tips, pull requests merged in 2021-12, with the labels that each got.

#27 RFC: REST Node API
  text/0026-rest-api/0026-rest-api.md
  text/0026-rest-api/0026-rest-api.yaml
Labels: ready for testnet, deployed on testnet

#10 RFC: Mnemonic Ternary Seed
  text/0010-mnemonic-ternary-seed/0010-mnemonic-ternary-seed.md
Labels: documentation

#33 RFC: Node Event API
  text/0033-node-event-api/0033-node-event-api.md
  text/0033-node-event-api/0033-node-event-api.yml
Labels: ready for testnet, deployed on testnet

#28 RFC: ED25519 Validation
  text/0028-ed25519-validation/0028-ed25519-validation.md
  text/0028-ed25519-validation/0028-test.json
Labels: ready for testnet
