Repository iotaledger/tips, pull requests merged in 2022-07, with the labels that each got.

#70 TIP-31 Bech32 Address Format (updated)
  tips/TIP-0031/tip-0031.md
Labels: Standards, Interface, Draft

#41 TIP-21 Serialization Primitives
  tips/TIP-0006/tip-0006.md
  tips/TIP-0007/tip-0007.md
  tips/TIP-0008/tip-0008.md
  tips/TIP-0021/tip-0021.md
Labels: Standards, Core, Draft

#74 TIP-34 Wotsicide (Stardust)
  tips/TIP-0034/tip-0034.md
Labels: Standards, Core, Draft

#43 TIP-22 IOTA Protocol Parameters
  tips/TIP-0022/tip-0022.md
Labels: Standards, Core, Draft

#54 TIP-23 Tagged Data Payload
  tips/TIP-0023/tip-0023.md
Labels: Standards, Core, Draft

#62 TIP-26 UTXO Indexer REST API
  tips/TIP-0026/indexer-rest-api.yaml
  tips/TIP-0026/tip-0026.md
Labels: Standards, Interface, Draft

#68 TIP-30 Native Token Metadata Standard
  tips/TIP-0030/examples/1-valid.json
  tips/TIP-0030/examples/2-valid.json
  tips/TIP-0030/examples/3-invalid.json
  tips/TIP-0030/irc30.schema.json
  tips/TIP-0030/tip-0030.md
Labels: Standards, IRC, Draft

#71 TIP-32 Shimmer Protocol Parameters
  tips/TIP-0032/tip-0032.md
Labels: Standards, Core, Draft

#55 TIP-24 Tangle Block (Stardust)
  tips/TIP-0024/tip-0024.md
Labels: Standards, Core, Draft
